# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d61b3fe0557922c8a61e75d7fe4d5deca7332d08ee42f01e06a866c44cc87ea48b5e982fd396080393318f8aaaf61c4d34bd83cff5fecdea7d7a0182f6111020

test:
  secret_key_base: 8dc85e7e1516278ee9a93025de4958ced857bbf8f36e9ee48c860eccf683e62e5b3fcda6426688a2412bff15a594152aa32979f26c2d43d276c61be38ccde2d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
